main: com.stardevllc.starcore.StarCore
version: ${version}
api-version: 1.13
name: ${name}
author: Firestar311
depend: [NBTAPI]
softdepend: [mcMMO, PlaceholderAPI]
commands: 
  starcore: 
  staritems: 
  starmclib: